# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 12:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170822_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
