# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_meme_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
    ]
